configfile: "Smake/config.yaml"

# https://github.com/snakemake/snakemake/issues/179
# container: "docker://continuumio/miniconda3:4.8"

rule all:
    input:
        ""

rule rule1:
    input:
        "data/"
    output:
        "data/processed/"
    conda:
        "Smake/environments/"
    shell:
        """
        
        """

rule rule2:
    input:
        "data/"
    output:
        "data/processed/"
    conda:
        "Smake/environments/"
    script:
        "code/"